In [7]:
import numpy as np

daily_sales = np.arange(16)

reshaped_sales = daily_sales.reshape(4, 4)

auto_reshape = daily_sales.reshape(4, -1)

print("Original daily sales:", daily_sales)
print("Reshaped sales (3x4):\n", reshaped_sales)
print("Auto reshaped sales (3x4):\n", auto_reshape)

Original daily sales: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped sales (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Auto reshaped sales (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [9]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

v_stacked = np.vstack((array1, array2))
h_stacked = np.hstack((array1, array2))

print("Vertically stacked array:\n", v_stacked)
print("Horizontally stacked array:\n", h_stacked)

Vertically stacked array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontally stacked array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
