In [14]:
import numpy as np

daily_sales = np.arange(16)

reshaped_sales = daily_sales.reshape(4, 4)

auto_reshape = daily_sales.reshape(4, -1)

print("Original daily sales:", daily_sales)
print("Reshaped sales (3x4):\n", reshaped_sales)
print("Auto reshaped sales (3x4):\n", auto_reshape)

Original daily sales: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped sales (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Auto reshaped sales (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

v_stacked = np.vstack((array1, array2))
h_stacked = np.hstack((array1, array2))

print("Vertically stacked array:\n", v_stacked)
print("Horizontally stacked array:\n", h_stacked)

Vertically stacked array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontally stacked array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [22]:
import pandas as pd
import numpy as np

# Generate synthetic regression data
np.random.seed(42)
X = np.linspace(1, 50, 50)
noise = np.random.normal(0, 3, 50)
Y = 2.5 * X + 10 + noise  # Linear relation with noise

# Create DataFrame
df = pd.DataFrame({
    "X": X,
    "Y": Y
})

# Save to Excel
print("DataFrame head:\n", df)


DataFrame head:
        X           Y
0    1.0   13.990142
1    2.0   14.585207
2    3.0   19.443066
3    4.0   24.569090
4    5.0   21.797540
5    6.0   24.297589
6    7.0   32.237638
7    8.0   32.302304
8    9.0   31.091577
9   10.0   36.627680
10  11.0   36.109747
11  12.0   38.602811
12  13.0   43.225887
13  14.0   39.260159
14  15.0   42.325247
15  16.0   48.313137
16  17.0   49.461507
17  18.0   55.942742
18  19.0   54.775928
19  20.0   55.763089
20  21.0   66.896946
21  22.0   64.322671
22  23.0   67.702585
23  24.0   65.725755
24  25.0   70.866852
25  26.0   75.332768
26  27.0   74.047019
27  28.0   81.127094
28  29.0   80.698084
29  30.0   84.124919
30  31.0   85.694880
31  32.0   95.556835
32  33.0   92.459508
33  34.0   91.826867
34  35.0   99.967635
35  36.0   96.337469
36  37.0  103.126591
37  38.0   99.120990
38  39.0  103.515442
39  40.0  110.590584
40  41.0  114.715400
41  42.0  115.514105
42  43.0  117.153055
43  44.0  119.096689
44  45.0  118.064434
45  46.0  122.840